# variáveis
@port_url = http://localhost:5000
###
# create task
POST {{port_url}}/tasks
Content-Type: application/json

{
  "title": "Estudar",
  "description": "Estudar Matemática"
}

HTTP/1.1 200  - OK
server: Werkzeug/3.0.1 Python/3.11.5
date: Mon, 22 Jan 2024 22:33:57 GMT
content-type: application/json
content-length: 50
connection: close
###
# list tasks
GET {{port_url}}/tasks

HTTP/1.1 200  - OK
server: Werkzeug/3.0.1 Python/3.11.5
date: Mon, 22 Jan 2024 22:34:02 GMT
content-type: application/json
content-length: 204
connection: close
###
# return task by id
GET {{port_url}}/tasks/1388b033-10af-4c4d-872b-561496d94586

HTTP/1.1 200  - OK
server: Werkzeug/3.0.1 Python/3.11.5
date: Mon, 22 Jan 2024 22:36:02 GMT
content-type: application/json
content-length: 139
connection: close
###
PUT {{port_url}}/tasks/1388b033-10af-4c4d-872b-561496d94586
Content-Type: application/json

{
  "title": "Estudar",
  "description": "Estudar Portugues 2"
}

HTTP/1.1 404  - NOT FOUND
server: Werkzeug/3.0.1 Python/3.11.5
date: Mon, 22 Jan 2024 22:40:48 GMT
content-type: application/json
content-length: 68
connection: close