# variáveis
@port_url = http://localhost:5000
###
# create task
POST {{port_url}}/tasks
Content-Type: application/json

{
  "title": "Estudar",
  "description": "Estudar História"
}

HTTP/1.1 200  - OK
server: Werkzeug/3.0.1 Python/3.11.5
date: Mon, 22 Jan 2024 22:55:30 GMT
content-type: application/json
content-length: 50
connection: close
###
# list tasks
GET {{port_url}}/tasks

HTTP/1.1 200  - OK
server: Werkzeug/3.0.1 Python/3.11.5
date: Mon, 22 Jan 2024 22:56:35 GMT
content-type: application/json
content-length: 362
connection: close
###
# return task by id
GET {{port_url}}/tasks/59f3e7fd-6b38-4426-bc01-3787361a937a

HTTP/1.1 200  - OK
server: Werkzeug/3.0.1 Python/3.11.5
date: Mon, 22 Jan 2024 22:56:04 GMT
content-type: application/json
content-length: 136
connection: close
###
PUT {{port_url}}/tasks/59f3e7fd-6b38-4426-bc01-3787361a937a
Content-Type: application/json

{
  "title": "Estudar",
  "description": "Estudar História",
  "completed": true
}

HTTP/1.1 200  - OK
server: Werkzeug/3.0.1 Python/3.11.5
date: Mon, 22 Jan 2024 22:55:58 GMT
content-type: application/json
content-length: 49
connection: close
###
DELETE {{port_url}}/tasks/59f3e7fd-6b38-4426-bc01-3787361a937a

HTTP/1.1 200  - OK
server: Werkzeug/3.0.1 Python/3.11.5
date: Mon, 22 Jan 2024 22:56:28 GMT
content-type: application/json
content-length: 47
connection: close